#!/usr/bin/env python3.7

from sys import path
import signal
path.append("/usr/local/share/networkmgr")
from src.trayicon import TrayIcon

signal.signal(signal.SIGINT, signal.SIG_DFL)

i = TrayIcon()
i.tray()
